# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np)

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr_memory = arr.nbytes

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr = np.zeros(10)
arr[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
arr = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [28]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [37]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
np.random.rand(3, 3, 3)

array([[[0.99624818, 0.50400473, 0.00841349],
        [0.45542225, 0.39584228, 0.9583976 ],
        [0.22360506, 0.14351086, 0.77833405]],

       [[0.68630633, 0.89556561, 0.70392765],
        [0.77168698, 0.35073575, 0.46889912],
        [0.47426972, 0.15530936, 0.62984107]],

       [[0.61074984, 0.42660743, 0.78422385],
        [0.52770828, 0.1810257 , 0.53482693],
        [0.25643599, 0.56911837, 0.93735798]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
arr = np.random.rand(10, 10)
min_r = arr.min()
max_r = arr.max()
print(min_r, max_r)

0.03791850710970457 0.9964222814404063


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.rand(30)
print(arr.mean())

0.5040529982916272


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [66]:
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
matrix = np.ones((3, 3))
matrix = np.pad(matrix, 1, mode='constant', constant_values=0)
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [42]:
print(np.isnan(0 * np.nan))
print((np.nan == np.nan) == False)
print((np.inf > np.nan) == False)
print(np.isnan(np.nan - np.nan))
print((np.nan in set([np.nan])) == True)
print((0.3 == 3 * 0.1) == False)

True
True
True
True
True
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros(64).reshape(8, 8)
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [92]:
np.unravel_index(indices=100, shape=(6, 7, 8))

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
patron = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(patron, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.rand(5, 5)
matrix1 = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(matrix.min())
print(matrix.max())
print(matrix)
print(matrix1)

0.024286937745973236
0.9791417235868985
[[0.86991775 0.85086722 0.42922426 0.24194257 0.7825237 ]
 [0.73635839 0.43106751 0.130483   0.59706199 0.28396322]
 [0.36513467 0.72595915 0.42802652 0.61421765 0.02428694]
 [0.45674231 0.6756063  0.93000268 0.87735242 0.97914172]
 [0.78939512 0.44147662 0.18533809 0.1504149  0.68645301]]
[[0.88561195 0.86566072 0.42408262 0.22794632 0.79408594]
 [0.74573795 0.42601302 0.11121698 0.59985566 0.27195368]
 [0.3569629  0.73484704 0.42282825 0.61782244 0.        ]
 [0.45290172 0.68211352 0.94853768 0.89339813 1.        ]
 [0.80128224 0.43691427 0.1686656  0.13209125 0.69347306]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [111]:
color_dtype = np.dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])
print(color_dtype)
red = np.array((255, 0, 0, 255), dtype=color_dtype)
print(red)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [113]:
matrix_a = np.random.rand(5, 3)
matrix_b = np.random.rand(3, 2)
matrix_c = matrix_a @ matrix_b
print(matrix_c)

[[1.12038661 0.84137857]
 [0.53775992 0.18219896]
 [1.71372453 1.00889442]
 [1.81597394 1.1401984 ]
 [1.22691113 0.95610175]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
arr = np.arange(15)
mask = (arr > 3) & (arr < 8)
arr[mask] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
# sum([0, 1, 2, 3, 4], start=-1) = -1 + 0 + 1 + 2 + 3 + 4 = 9
# from numpy import *
# ES PELIGROSO PORQUE AL IMPORTAR AS * SOBREESCRIBE FUNCIONES DE PYTHON PURO. POR ESO HAY QUE PONER IMPORT AS NP
print(sum(range(5),-1))
# AHORA ES np.sum([0, 1, 2, 3, 4], axis=-1) = 0 + 1 + 2 + 3 + 4 = 10 # axis indica el eje sobre el que sumar. 
                                                            # axis=0 → suma por columnas
                                                            # axis=1 → suma por filas
                                                            # axis=-1 → suma sobre el último eje

import numpy as np                                             

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [35]:
Z = np.arange(5)
Z**Z            # Potencia el array elemento a elemento:  Al comprobar me da: Z**Z = [0**0, 1**1, 2**2, 3**3, 4**4] = array([  1,   1,   4,  27, 256]). No lo entiendo.
2 << Z >> 2     # 2 << n >> 2 = multiplicar por 2^n y luego dividir entre 4: array([0, 1, 2, 4, 8])
Z <- Z          # Es una comparación encadenada. Z < -Z = [0 < 0, 1 < -1, 2 < -2, 3 < -3, 4 < -4]: array([False, False, False, False, False])
1j*Z            # Aqui esta multiplicando el número imaginario (i en matemáticas) 1j por el array. Al comprobar veo que esta modificando el array y asignando la variable a cada número y convirtiendolo en float: array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])
Z/1/1           # Aqui divide 2 veces entre 1. Al dividir Numpy siempre convierte enn float: array([0., 1., 2., 3., 4.])
# Z<Z>Z           # Python intenta evaluar esto como comparación encadenada. Entiende: (Z < Z) and (Z > Z). Pero arrays no se pueden usar con 'and'. Sería necesario: (Z < Z) & (Z > Z). Al comprobar me da: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Respuesta: Todas son legales excepto Z<Z>Z

array([0., 1., 2., 3., 4.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) # División por cero devuelve 'nan' porque 0/0 es indeterminado matemáticamente.
np.array(0) // np.array(0) # División entera por 0 devuelve 0 por convención en Numpy. Avisa pero no crashea.
arr = np.array([np.nan]).astype(int).astype(float) # Crea un array con 'nan' (dtype: float64). Luego convierte a int pero no puede porque 'nan' no es un valor entero válido. Por último convierte a float. Da [-9.22337204e+18] y avisa del error.
print(arr) # LECCIÓN: NUMPY INTENTA NO CRASHEAR.

[-9.22337204e+18]


/tmp/ipykernel_2269/62753306.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # División por cero devuelve 'nan' porque 0/0 es indeterminado matemáticamente.
/tmp/ipykernel_2269/62753306.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # División entera por 0 devuelve 0 por convención en Numpy. Avisa pero no crashea.
/tmp/ipykernel_2269/62753306.py:3: RuntimeWarning: invalid value encountered in cast
  arr = np.array([np.nan]).astype(int).astype(float) # Crea un array con 'nan' (dtype: float64). Luego convierte a int pero no puede porque 'nan' no es un valor entero válido. Por último convierte a float. Da [-9.22337204e+18] y avisa del error.


#### 29. How to round away from zero a float array ? (★☆☆)

In [6]:
arr = np.array([2.6, 4.3, -6.4, -1.5])
np.sign(arr) * np.ceil(np.abs(arr))

array([ 3.,  5., -7., -2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
np.intersect1d(arr1, arr2)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Para ignorar TODOS los warnings de pandas, numpy, etc...
"import warnings"
"warnings.filterwarnings('ignore')"
# 'ignore' → Ignorar todos
# 'error' → Convertir warnings en errores
# 'always' → Mostrar siempre
# 'default' → Comportamiento por defecto

# La forma de numpy haciendo que después del bloque del código que genera el warning se restauren los warnings es (ESTO SE LLAMA 'CONTEXT MANAGER'):
old_settings = np.seterr(all='ignore')
# Código que genera warnings:
result = np.array(0) / np.array(0)
np.seterr(**old_settings) # Restaura la configuración


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [13]:
# np.sqrt(-1) == np.emath.sqrt(-1) → False

# En matemáticas de números reales:
# La raíz cuadrada de -1 NO existe porque no hay número real cuyo cuadrado sea negativo
# Por eso: np.sqrt(-1) = nan

# En matemáticas de números complejos:
# Se inventó la unidad imaginaria: i² = -1
# Entonces: √(-1) = i
# Por eso: np.emath.sqrt(-1) = 1j (1j es i en Python)

# emath = Extended Math (matemáticas extendidas a complejos)

# Ejemplos:
# np.sqrt(-1) = nan
# np.emath.sqrt(-1) = 1j
# np.emath.sqrt(4) = (2+0j)
# np.emath.sqrt(-4) = 2j  → porque (2j)² = 4j² = 4(-1) = -4

# Respuesta: False (nan != 1j)
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


/tmp/ipykernel_2348/2016595874.py:21: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))  # False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
print(f'Yesterday: {yesterday}\nToday: {today}\nTomorrow: {tomorrow}')

Yesterday: 2026-03-03
Today: 2026-03-04
Tomorrow: 2026-03-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [22]:
july16_dates = np.datetime64('2016-07-01') + np.timedelta64(1, 'D') * np.arange(31)
print(july16_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([2, 2, 2], dtype=float)

np.add(A, B, out=B)

np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -4.  -7.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
random_arr = np.random.uniform(0, 10, 10)
metodo1 = random_arr.astype(int)
metodo2 = np.floor(random_arr)
metodo3 = np.trunc(random_arr)
metodo4 = random_arr - random_arr % 1
metodo5 = np.modf(random_arr)[1]
print(f"Array original:\n{random_arr}")
print(f"Método 1 (astype):\n{metodo1}")
print(f"Método 2 (floor):\n{metodo2}")
print(f"Método 3 (trunc):\n{metodo3}")
print(f"Método 4 (resta decimal):\n{metodo4}")
print(f"Método 5 (modf): {metodo5}")

[6.68370819 4.4118581  2.82929067 9.46448286 7.54593416 0.79012069
 1.2658407  0.52252716 2.63045966 7.13887165]
Método1: [6 4 2 9 7 0 1 0 2 7]
Método2: [6. 4. 2. 9. 7. 0. 1. 0. 2. 7.]
Método3: [6. 4. 2. 9. 7. 0. 1. 0. 2. 7.]
Método4: [6. 4. 2. 9. 7. 0. 1. 0. 2. 7.]
Método5: [6. 4. 2. 9. 7. 0. 1. 0. 2. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

arr = np.fromiter(fibonacci(10), dtype=int)

print(arr)

[ 0  1  1  2  3  5  8 13 21 34]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [46]:
vector = np.random.rand(10)
sorted_vector = np.sort(vector)
print(sorted_vector)

[0.33771867 0.59130678 0.66271214 0.67112008 0.68889573 0.68917857
 0.70129664 0.76748018 0.81494315 0.83130536]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [48]:
arr = np.array([1, 2])
sum(arr)

np.int64(3)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [51]:
arr1 = np.random.rand(25)
arr2 = np.random.rand(25)
np.array_equal(arr1, arr2)  # Todos los elementos idénticos (True/False)
np.allclose(arr1, arr2)           # Todos los elementos aproximadamente iguales (True/False)
arr1 == arr2                # Cada elemento individualmente (Array de True/False)
(arr1 == arr2).all()              # Si todos son iguales (True/False)

np.False_

#### 43. Make an array immutable (read-only) (★★☆)

In [25]:
arr = np.array([0, 1, 2])
print(f"Is the array mutable before 'arr.flags.writeable = False' ? {arr.flags.writeable}")
arr.flags.writeable = False
print(f"Is the array mutable after 'arr.flags.writeable = False' ? {arr.flags.writeable}")
# Si hacemos (arr[0] = 999) da ValueError: assignment destination is read-only

Is the array mutable before 'arr.flags.writeable = False' ? True
Is the array mutable after 'arr.flags.writeable = False' ? False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [27]:
matrix = np.random.rand(10, 2)
x = matrix[:, 0]
y = matrix[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)
grados = np.degrees(theta)
print(f"Cartesianas:\n{matrix}")
print(f"r (radio):\n{r}")
print(f"θ (ángulo):\n{theta}")
print(f"Grados:\n{grados}")

Cartesianas:
[[0.83760769 0.00639387]
 [0.4975696  0.28270283]
 [0.58588764 0.93770874]
 [0.07090199 0.64951655]
 [0.94433022 0.2132327 ]
 [0.32789745 0.18219204]
 [0.66076113 0.58393704]
 [0.69179958 0.56692952]
 [0.04792344 0.08622346]
 [0.08847591 0.5945738 ]]
r (radio):
[0.83763209 0.57227301 1.10569526 0.65337496 0.96810524 0.37511422
 0.88180936 0.89442481 0.09864655 0.60112062]
θ (ángulo):
[0.00763335 0.51668425 1.01233531 1.46206567 0.22207872 0.50716092
 0.7237553  0.68651841 1.0635071  1.4230747 ]
Grados:
[ 0.4373585  29.60382688 58.00254066 83.77019223 12.72417344 29.05818052
 41.4681241  39.33460722 60.9344682  81.53617422]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

[0.89356091 0.         0.51192862 0.1663217  0.09051369 0.07205815
 0.32868677 0.09590494 0.74199828 0.06750291]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [40]:
dtype = np.dtype([('x', float), ('y', float)])

x_values = np.linspace(0, 1, 5)
y_values = np.linspace(0, 1, 5)

xx, yy = np.meshgrid(x_values, y_values)

coords = np.zeros(25, dtype=dtype)
coords['x'] = xx.flatten()
coords['y'] = yy.flatten()
print(coords)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [52]:
X = np.array([1, 2, 3])
Y = np.array([4, 5])

cauchy = 1 / np.subtract.outer(X, Y)
print(cauchy)

[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64, np.float32, np.float64]:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
    else:
        info = np.finfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}")

int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [68]:
arr = np.arange(1000)
np.set_printoptions(threshold=np.inf)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [74]:
arr = np.array([1.5, 3.2, 7.8, 2.1, 9.4])
seeked_value = 3.0
value = arr[np.argmin(np.abs(arr - seeked_value))]
print(value)

3.2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)